### ISSUE TITLE
Add strikethrough effect when todo is completed

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/web-todo#1]
Currently when you complete a todo there is no changes to the text. User expect there will be some styling to the completed todo. At least a strikethrough will do.

**Comment by amadzuki** [comment]
It is done but I think it still need some beautification. 

Will have to complete:

- CSS tricks
    - recon codepen, etc. and try to implement
- Animation
    - a simple one will do

**Comment by mhaidarhanif** [comment]
For the comments you can simplify them:

Before:

<img width="426" alt="Screenshot 2020-05-14 at 15 01 40" src="https://user-images.githubusercontent.com/235584/81903169-edf3f080-95f3-11ea-9830-543aa9d8fe1d.png">

After:

<img width="451" alt="Screenshot 2020-05-14 at 15 02 17" src="https://user-images.githubusercontent.com/235584/81903176-f0eee100-95f3-11ea-9610-28a70530fe39.png">
