### ISSUE TITLE
Is there a better way to pass data to another function?

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/web-todo#5]
https://github.com/amadzuki/web-todo/blob/291f28d9a353d3ebe4de5e1b571f49149f98d801/index.js#L174

**Comment by mhaidarhanif** [comment]
There is an alternative. It's better to pass a parameter in the handler function, but you will be required to both put the `id`/`index` as an attribute and use `this`. Also, some other refactoring might be needed.

```js
// ...
sideMenuTodoRemove.addEventListener("click", (event) => {
  const clickedTodoIndex = this.getAttribute("data-id")
  removeTodo(clickedTodoIndex)
})
// ...
```

```js
const removeTodo = (clickedTodoIndex) => {
  const todoIndex = clickedTodoIndex
  // ...
}
```

This is just a sudden tip of advice. You might use it later on, it's okay to not use it in this project.
